arrow_spacing: {level: 'error'}
empty_constructor_needs_parens: {level: 'error'}
non_empty_constructor_needs_parens: {level: 'error'}
no_trailing_whitespace: {level: 'error'}
no_empty_param_list: {level: 'error'}
no_stand_alone_at: {level: 'error'}
no_backticks: {level: 'ignore'}
no_implicit_braces: {level: 'ignore'}
no_implicit_parens: {level: 'error'}
space_operators: {level: 'error'}
